### ISSUE TITLE
icc-profile not work

### ISSUE THREAD

**Issue by ShiroNek0** [suhteevah/mpvhq-win64#1]
icc-profile option doesn't work. I use: vo=opengl-vhq:icc-profile="C:\App\MPV\U2414H.icm"

![mpv](https://cloud.githubusercontent.com/assets/10398767/6965281/7596abea-d97a-11e4-9829-1e7faca0e60f.png)

**Comment by suhteevah** [comment]
I downloaded an icm for that monitor and passed
vo=opengl-vhq:icc-profile=~~/U2414H.icm
the .icm is in the file with the .exe.
Its working fine on my end.  So please post your .icm.
Try using [C:\App\MPV\U2414H.icm], brackets instead of quotes if you want to pass it the file location like that.

**Comment by ShiroNek0** [comment]
I try the lastest build with your option but still not work. 

I use the same profile with you, the exe downloaded from Dell website. 

Beside, I don't think problem in icm file or bracket because error message is "Option not found", which is usually happened when missing depedency. If it cannot open profile, message should be "Cannot open..." IIRC.

It works on your computer, so can't be missing dependency. Strange...

Profile: http://a.pomf.se/ckurjg.icm

**Comment by suhteevah** [comment]
I'm looking into what else I need to compile with.  It's indeed throwing this error for me now.
compiling with icc support atm, will push soon.
Pushed the update, try the new .exe seems to be fixed!

**Comment by ShiroNek0** [comment]
Thanks, with lcms2 it seems to be ok now.
