### ISSUE TITLE
Example config file is strange

### ISSUE THREAD

**Issue by haasn** [suhteevah/mpvhq-win64#2]
1. There's no reason to specify `hwdec=no` since it's the default.
2. The commented line 9 is fairly redundant and highly subjective.
3. The cache settings don't really make sense as a default.
4. `save-position-quit`, `really-quiet` and `keep-open` all shouldn't be default.

`really-quiet` in particular is a huge offender, it just basically made me spend 15 minutes trying to debug why your mpvhq builds weren't working properly (the console would always result in a blank, blinking cursor). Can you name a single reason why this is made default?

**Comment by suhteevah** [comment]
fixed
