### ISSUE TITLE
MPV eats memory while minimized

### ISSUE THREAD

**Issue by kickafetus** [suhteevah/mpvhq-win64#4]
![mpv memory](https://cloud.githubusercontent.com/assets/9096271/7257405/1e3f2f16-e81b-11e4-971d-b3f40c401378.PNG)
When MPV is minimized and playing a file it will leak memory and will not stop. And when brought back to the foreground it will drop back to ~160M

**Comment by suhteevah** [comment]
I don't have this issue if you continue to experience it open a ticket on mainline mpv.
