### ISSUE TITLE
ytdl options dont exist?

### ISSUE THREAD

**Issue by chaquator** [suhteevah/mpvhq-win64#5]
I found out that ytdl options arent in this build, [even though it's listed in mpvhq's github docs](https://github.com/haasn/mpvhq/blob/master/DOCS/man/options.rst)

[regular mpv's options](http://pastebin.com/iCf29FK5)
[mpvhq-win64's options](http://pastebin.com/dFw7eBnv)

what's missing:

```
--dvd-angle
--dvd-device
--dvd-speed
--load-scripts
--osc
--script
--script-opts
--ytdl
--ytdl-format
--ytdl-raw-options
```

Why is this so?

i guess this should be pushed to mpvhq itself

for now, though, i'll revert back to rev. 69 where everything works until this gets fixed

**Comment by suhteevah** [comment]
Should be fixed let me know.

**Comment by chaquator** [comment]
seems to be the same at rev. 72
`Error parsing option ytdl-options (option not found)
C:/Custom Programs/mpv/mpv.conf:2: setting option ytdl-options='bestvidoe+bestaudio' failed.
Error parsing option no-osc (option not found)
C:/Custom Programs/mpv/mpv.conf:19: setting option no-osc='' failed.`

**Comment by ghost** [comment]
Been having the same problem. OSC also doesn't work for some reason.

**Comment by suhteevah** [comment]
@AliceTertia @Chaquator should be fixed let me know.

**Comment by chaquator** [comment]
somehow still no
![untitled](https://cloud.githubusercontent.com/assets/5050923/8745046/7fdd3e56-2c41-11e5-8a06-7b954de3dc54.png)

**Comment by suhteevah** [comment]
Try without bestvideo+bestaudio, and you have a mis-type in your option.

**Comment by chaquator** [comment]
woops lol
ye its fixed
ty

**Comment by suhteevah** [comment]
By the way @Chaquator best is the default option for yt-dl, so you don't need it.

**Comment by chaquator** [comment]
using the default doesnt enable 60 fps videos

**Comment by ghost** [comment]
Scripts, OSC and yt-dl are working, even with the bestvideo+bestaudio setting.
