### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by iyashikej** [suhteevah/mpvhq-win64#6]
I don't know what, but something changed in Windows 10 and mpv performance dropped so there's horrible stuttering in some video files (e.g. 400 dropped frames, while i had 0 in Win 8.1)

video-sync=display doesn't change anything

**Comment by suhteevah** [comment]
Can you get me a link to said file, haven't noticed any issues with mpv on w10 yet.

**Comment by iyashikej** [comment]
http://is.gd/RcLOvU
I cut first 30s (without reencoding of course), massive frame drop occurs at the beggining when camera slides vertically.
Using latest nvidia drivers.

**Comment by suhteevah** [comment]
Gonna need you to see if anything else is wrong on your side boss, just tried out that file and got 0 frames dropped.

**Comment by iyashikej** [comment]
Ok, changed power plan from adaptive to max performance in nvidia control panel and it's fixed.
Honestly I never thought this had any influence on anything...

**Comment by suhteevah** [comment]
Good to hear its fixed, best of luck!
